title: Hernandoâ€™s Blog
description: Notes on code, tools, and automation
author: Hernando Abella

theme: minima

# Base URL settings (IMPORTANT for GitHub Pages)
baseurl: ""
url: "https://hernandoabella.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed

# Navigation menu
header_pages:
  - index.md
  - blog.md
  - tags.md
  - categories.md
  - about.md

# Minima options
show_excerpts: true

minima:
  skin: dark

highlighter: rouge
