title: Hernandoâ€™s Blog
description: Notes on code, tools, and automation
url: https://hernandoabella.github.io

theme: minima
markdown: kramdown
permalink: /:categories/:title/

author:
  name: Hernando Abella

plugins:
  - jekyll-seo-tag
  - jekyll-feed
